FileStorageSystem/Models/FileSystemItem.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileStorageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileSystemItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileSystemItem()
        {
            this.SharedFiles = new HashSet<SharedFile>();
        }
    
        public System.Guid FileSystemItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public System.DateTime CreatingDate { get; set; }
        public double FileSize { get; set; }
        public Nullable<System.Guid> ParentFolderID { get; set; }
        public string PhysicalPath { get; set; }
        public int TypeOfSystemItemID { get; set; }
        public Nullable<System.Guid> OwnerID { get; set; }
        public int IsSharedToAll { get; set; }
        public int isApproved { get; set; }
        public int ItemId { get; set; }
        public string FileExtensionId { get; set; }
        public int AreaId { get; set; }
        public int RegionId { get; set; }
    
        public  Area Area { get; set; }
        public  Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<SharedFile> SharedFiles { get; set; }
        public  User User { get; set; }
    }
}

FileStorageSystem/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FileStorageSystem.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Net;
using System.Net.Mail;
using System.Web.Configuration;
using System.Threading.Tasks;
using FileStorageSystem.ViewModels;
using System.Drawing;
using System.Drawing.Drawing2D;
using FileStorageSystem.Common;

namespace FileStorageSystem.Controllers
{
    public class FileController : Controller
    {
        private static NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();

        public ActionResult UploadFiles(IEnumerable<HttpPostedFileBase> files)
        {
            HttpPostedFileBase file = files.First();
            Session["UploadedFile"] = null;
            if (file != null)
            {
                string fileExtension = Path.GetExtension(file.FileName).Replace(".", "");
                Guid fileId = Guid.NewGuid();
                string physicalPath = Path.Combine(Server.MapPath("~/App_Data"), fileId.ToString() + "." + fileExtension);

                Session["UploadedFile"] = new PhysicalFileViewModel()
                {
                    FileExtension = fileExtension,
                    fileId = fileId,
                    PhysicalPath = physicalPath,
                    FileSize = file.ContentLength
                };

                try
                {
                    file.SaveAs(physicalPath);
                }
                catch (Exception ex)
                {
                    logger.Error(string.Format("type: " + ex.GetType() + "---Target: " + ex.TargetSite + "---Message: " + ex.Message), ex);
                }

            }

            return Content("");
        }

        [HttpPost]
        public ActionResult SaveToDatabase(string description, string parentFolder, string isShared, string[] shareUsers, string FileName, int areaId, int regionId)
        {
            FileStorageSystemContext context = new FileStorageSystemContext();
            PhysicalFileViewModel uploadedFile = (PhysicalFileViewModel)Session["UploadedFile"];

            string uploadStatus = string.Empty;
            string userName = this.User.Identity.Name.Split('\\')[1];

            Guid userId = context.Users.Where(u => u.UserName == userName).First().UserID;

            FileSystemItem nItem = new FileSystemItem()
            {
                FileSystemItemID = uploadedFile.fileId,
                CreatingDate = DateTime.Now,
                FileSize = uploadedFile.FileSize,
                ItemName = FileName,
                TypeOfSystemItemID = 2,
                PhysicalPath = uploadedFile.PhysicalPath,
                ItemDescription = description,
                ParentFolderID = Guid.Parse(parentFolder),
                IsSharedToAll = isShared == "True" ? 1 : 0,
                OwnerID = userId,
                isApproved = 0,
                FileExtensionId = uploadedFile.FileExtension,
                AreaId = areaId,
                RegionId = regionId
            };
            context.FileSystemItems.Add(nItem);

            if (shareUsers != null)
            {
                foreach (var user in ConvertAutoCompleteToList(shareUsers))
                {
                    SharedFile shrdf = new SharedFile()
                    {
                        UserId = user.UserID,
                        SharedFileID = Guid.NewGuid(),
                        FileId = nItem.FileSystemItemID
                    };
                    context.SharedFiles.Add(shrdf);
                }
                context.SaveChanges();
            }

            try
            {
                var scresult = context.SaveChanges();
                Task.Factory.StartNew(() => MessageService.SendToAdminsApproveEmail(nItem, GetMainUrl()));
                uploadStatus = "successfully";
            }
            catch (Exception ex)
            {
                logger.Error(string.Format("type: " + ex.GetType() + "---Target: " + ex.TargetSite + "---Message: " + ex.Message), ex);
                uploadStatus = "Something wrong! The file didn't uploaded";
            }

            Session["UploadedFile"] = null;

            return Json(new { status = uploadStatus, target = FileName });
        }

        private string GetMainUrl()
        {
            var tempUrl = Request.Url;
            string url = tempUrl.Authority + string.Join(null, tempUrl.Segments, 0, (tempUrl.Segments.Length - 2));
            return url;
        }


        public ActionResult Delete(Guid itemId)
        {
            string message = string.Empty;

            if (itemId != null)
            {
                int res = DeleteItem(itemId);
                if (res == 1)
                {
                    message = "error";
                }
            }
            return Json(message, JsonRequestBehavior.AllowGet);

        }


        public int DeleteItem(Guid itemId)
        {
            using (FileStorageSystemContext context = new FileStorageSystemContext())
            {
                foreach (SharedFile file in context.SharedFiles.Where(f => f.FileId == itemId).ToList())
                {
                    context.SharedFiles.Remove(file);
                    context.SaveChanges();
                }
            }
            FileSystemItem deletedFile;
            using (FileStorageSystemContext context = new FileStorageSystemContext())
            {
                deletedFile = context.FileSystemItems.Where(x => x.FileSystemItemID == itemId).FirstOrDefault();
                if (deletedFile != null)
                {
                    context.FileSystemItems.Remove(deletedFile);
                    context.SaveChanges();
                }
                else { return 1; }
            }
            if (deletedFile.TypeOfSystemItemID == (int)TypeOfStorageItem.FILE)
            {
                return 0;
            }
            var childItems = from child in new FileStorageSystemContext().FileSystemItems
                             where child.ParentFolderID == itemId
                             select child.FileSystemItemID;

            if (childItems.Count() != 0)
            {
                foreach (var fileItem in childItems)
                {
                    DeleteItem(fileItem);
                }
            }
            return 0;
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult EditItem(FileItemViewModel item, string[] users)
        {
            if (item != null && ModelState.IsValid)
            {
                FileStorageSystemContext context = new FileStorageSystemContext();
                FileSystemItem editedItem = context.FileSystemItems.First(f => f.FileSystemItemID == item.FileSystemItemID);

                editedItem.CreatingDate = item.CreatingDate;
                editedItem.isApproved = item.isApproved;
                editedItem.IsSharedToAll = item.IsSharedToAll;
                editedItem.ItemName = item.ItemName;
                editedItem.ItemDescription = item.ItemDescription;
                editedItem.TypeOfSystemItemID = item.TypeOfSystemItemID;
                editedItem.ParentFolderID = item.ParentFolderID;
                editedItem.FileSystemItemID = item.FileSystemItemID;
                editedItem.AreaId = item.AreaId;
                editedItem.RegionId = item.RegionId;

                ShareToAll(editedItem, item.IsSharedToAllBool);

                context.Entry(editedItem).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();

                EditShareTo(users, item.FileSystemItemID);

                EditUploadedFile(item.FileSystemItemID);
            }

            return Json("", JsonRequestBehavior.AllowGet);
        }

        public void EditUploadedFile(Guid fileId)
        {
            FileStorageSystemContext context = new FileStorageSystemContext();
            FileSystemItem fileItem = context.FileSystemItems.First(f => f.FileSystemItemID == fileId);

            PhysicalFileViewModel uploadedFile = (PhysicalFileViewModel)Session["UploadedFile"];

            if (uploadedFile != null)
            {
                string userName = this.User.Identity.Name.Split('\\')[1];
                Guid userId = context.Users.Where(u => u.UserName == userName).First().UserID;

                var nItem = new FileSystemItem()
                {
                    FileSystemItemID = uploadedFile.fileId,
                    CreatingDate = DateTime.Now,
                    FileSize = uploadedFile.FileSize,
                    ItemName = fileItem.ItemName,
                    TypeOfSystemItemID = 2,
                    PhysicalPath = uploadedFile.PhysicalPath,
                    ItemDescription = fileItem.ItemDescription,
                    ParentFolderID = fileItem.ParentFolderID,
                    IsSharedToAll = fileItem.IsSharedToAll,
                    OwnerID = userId,
                    isApproved = 0,
                    FileExtensionId = uploadedFile.FileExtension,
                    AreaId = fileItem.AreaId,
                    RegionId = fileItem.RegionId
                };

                List<SharedFile> shared = context.SharedFiles.Where(s => s.FileId == fileItem.FileSystemItemID).ToList();
                List<SharedFile> sharedNew = new List<SharedFile>();

                if (shared.Count() == 0)
                {
                    try
                    {
                        context.FileSystemItems.Remove(fileItem);
                        context.SaveChanges();
                        context.FileSystemItems.Add(nItem);
                        var csresult = context.SaveChanges();
                        Task.Factory.StartNew(() => MessageService.SendToAdminsApproveEmail(nItem, GetMainUrl()));
                    }
                    catch (Exception ex)
                    {

FileStorageSystem/Views/Shared/EditorTemplates/Currency.cshtml
@model decimal?

@(Html.Kendo().CurrencyTextBoxFor(m => m)      
      .HtmlAttributes(new {style="width:100%"})
      .Min(0)
)

FileStorageSystem/Views/Shared/EditorTemplates/Date.cshtml
@model DateTime?

@(Html.Kendo().DatePickerFor(m => m))

FileStorageSystem/Views/Shared/EditorTemplates/DateTime.cshtml
@model DateTime?

@(Html.Kendo().DateTimePickerFor(m => m))

FileStorageSystem/Views/Shared/EditorTemplates/Email.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox" })

FileStorageSystem/Views/Shared/EditorTemplates/EmailAddress.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="email" })

FileStorageSystem/Views/Shared/EditorTemplates/FileSystemItem.cshtml
@model FileStorageSystem.ViewModels.FileItemViewModel

<script>
    var areaIndx='@Model.AreaId';
    var regionIndx='@Model.RegionId';
    var typeOfItem='@Model.TypeOfSystemItemID';
    var parFolderId='@Model.ParentFolderID';
</script>

<script src="@Url.Content("http://"+Request.Url.Authority + string.Join(null, Request.Url.Segments, 0, (Request.Url.Segments.Length - 2))+"Scripts/editFileItem.min.js")"></script>


@using (Html.BeginForm("EditItem","File",FormMethod.Post,new { id="editForm"+Model.AreaId+"_"+Model.RegionId }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal " style="margin-left:30px; margin-right:30px;">

		<div class="edit-upload">
			@Html.Label("Reload file")

			<input type="file" name="files" id="@("files"+Model.AreaId + "_" + Model.RegionId+"_")" />

		</div>

	    <div class="form-group">
	        @Html.Label("Name:")	        
	        <div class="col-md-10">
                @Html.TextBoxFor(m=>m.ItemName,new {id= "ItemName" + Model.AreaId + "_" + Model.RegionId })  
	        </div>
	    </div>
	    <div class="form-group">
	        @Html.Label("Description:")
	       
	        <div class="col-md-10">
	            @Html.TextAreaFor(m => m.ItemDescription, new {@class = "form-control", style = "width: 97%; resize:none", @rows = 4, id= "ItemDescription" + Model.AreaId + "_" + Model.RegionId })

	        </div>
	    </div>
		@Html.HiddenFor(model => model.AreaId)
		@Html.HiddenFor(model => model.CreatingDate)
		@Html.HiddenFor(model => model.ParentFolderID)
		@Html.HiddenFor(m => m.FileSystemItemID, new { id = "fsitem" + Model.AreaId + "_" + Model.RegionId })
		@Html.HiddenFor(m => m.isEditable, new { id = "isEditable" + Model.AreaId + "_" + Model.RegionId })
		@Html.HiddenFor(model => model.RegionId)
		@Html.HiddenFor(model => model.OwnerName)
		@Html.HiddenFor(model => model.TypeOfSystemItemID)
		@Html.HiddenFor(model => model.isApproved)
		
		<div id="@("isShrdAll"+Model.AreaId+"_"+Model.RegionId)">
            <label class="edit_checkbox">
                @Html.CheckBoxFor(m => m.IsSharedToAllBool, new Dictionary<string, object>
                {
                          { "id", "isShrdAll"+Model.AreaId+"_"+Model.RegionId }

                }) Is shared to all
        </label>	
		</div>
		

		@Html.Label("Share to: ")

		@(Html.Kendo().MultiSelect()
								.Name("editUsersMultiSelect" + Model.AreaId + "_" + Model.RegionId)
								.Placeholder("Select user...")
								.DataTextField("UserName")
								.DataValueField("UserName")
								.Placeholder("Select user...")
								.DataSource(source =>
								{
									source.Read(read =>
									{
										read.Action("GetUsers", "Grid");
									});
								})
		)

		<div style="margin-top:25px; text-align:center; margin-bottom:10px;">
			@(Html.Kendo().Button()
							.Name("SubmitEdit" + Model.AreaId + "_" + Model.RegionId)
							.HtmlAttributes(new { @class = "k-primary", style = "height:40px; margin-right:10px; width: 120px; padding-down:20px; " })
							.Content("Submit")
			)

			@(Html.Kendo().Button()
							.Name("cancelEdit" + Model.AreaId + "_" + Model.RegionId)
							.HtmlAttributes(new { style = "height:40px; width: 120px; padding-down:20px; " })
							.Content("Cancel")
							
			)
		</div>
	</div>
}

FileStorageSystem/Views/Shared/EditorTemplates/GridForeignKey.cshtml
@model object
           
@(
 Html.Kendo().DropDownListFor(m => m)        
        .BindTo((SelectList)ViewData[ViewData.TemplateInfo.GetFullHtmlFieldName("") + "_Data"])
)

FileStorageSystem/Views/Shared/EditorTemplates/Integer.cshtml
@model int?

@(Html.Kendo().IntegerTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%" })
      .Min(int.MinValue)
      .Max(int.MaxValue)
)

FileStorageSystem/Views/Shared/EditorTemplates/Number.cshtml
@model double?

@(Html.Kendo().NumericTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%" })
)

FileStorageSystem/Views/Shared/EditorTemplates/Password.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="password" })

FileStorageSystem/Views/Shared/EditorTemplates/String.cshtml
@model object 

@Html.Kendo().TextBoxFor(model => model)

FileStorageSystem/Views/Shared/EditorTemplates/Time.cshtml
@model DateTime?
           
@(Html.Kendo().TimePickerFor(m => m))

FileStorageSystem/Views/Shared/EditorTemplates/Url.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="url" })